//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YPYA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Surec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Surec()
        {
            this.KullaniciSurecs = new HashSet<KullaniciSurec>();
            this.Surec1 = new HashSet<Surec>();
        }
    
        public int Id { get; set; }
        public string Baslik { get; set; }
        public Nullable<System.DateTime> PlanBaslangic { get; set; }
        public Nullable<System.DateTime> PlanBitis { get; set; }
        public Nullable<int> Tamamlanan { get; set; }
        public Nullable<int> OlusturanId { get; set; }
        public Nullable<int> DurumId { get; set; }
        public Nullable<int> OncelikId { get; set; }
        public Nullable<int> ParentSurecId { get; set; }
        public Nullable<System.DateTime> OlusturmaTarihi { get; set; }
        public Nullable<int> ProjeId { get; set; }
        public Nullable<bool> haveChild { get; set; }
    
        public virtual Durum Durum { get; set; }
        public virtual Kullanici Kullanici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KullaniciSurec> KullaniciSurecs { get; set; }
        public virtual Oncelik Oncelik { get; set; }
        public virtual Proje Proje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Surec> Surec1 { get; set; }
        public virtual Surec Surec2 { get; set; }
    }
}
